# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class main_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setMinimumSize(QtCore.QSize(400, 300))
        Form.setMaximumSize(QtCore.QSize(400, 300))
        self.run = QtWidgets.QPushButton(Form)
        self.run.setGeometry(QtCore.QRect(205, 230, 100, 50))
        self.run.setObjectName("run")
        self.ChooseMethods = QtWidgets.QComboBox(Form)
        self.ChooseMethods.setGeometry(QtCore.QRect(50, 10, 240, 25))
        self.ChooseMethods.setCurrentText("")
        self.ChooseMethods.setObjectName("ChooseMethods")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 30, 25))
        self.label.setObjectName("label")
        self.file = QtWidgets.QLineEdit(Form)
        self.file.setGeometry(QtCore.QRect(50, 50, 240, 25))
        self.file.setObjectName("file")
        self.input1 = QtWidgets.QLineEdit(Form)
        self.input1.setGeometry(QtCore.QRect(50, 90, 240, 25))
        self.input1.setObjectName("input1")
        self.input2 = QtWidgets.QLineEdit(Form)
        self.input2.setGeometry(QtCore.QRect(50, 130, 240, 25))
        self.input2.setObjectName("input2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 30, 25))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 40, 25))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 40, 25))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 40, 25))
        self.label_5.setObjectName("label_5")
        self.input3 = QtWidgets.QLineEdit(Form)
        self.input3.setGeometry(QtCore.QRect(50, 170, 240, 25))
        self.input3.setObjectName("input3")
        self.choosefile = QtWidgets.QToolButton(Form)
        self.choosefile.setGeometry(QtCore.QRect(290, 50, 80, 25))
        self.choosefile.setObjectName("choosefile")
        self.option = QtWidgets.QPushButton(Form)
        self.option.setGeometry(QtCore.QRect(95, 230, 100, 50))
        self.option.setObjectName("option")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FP-DataHelper - 0.1.2"))
        self.run.setText(_translate("Form", "运行"))
        self.label.setText(_translate("Form", "方法："))
        self.label_2.setText(_translate("Form", "文件："))
        self.label_3.setText(_translate("Form", "参数1："))
        self.label_4.setText(_translate("Form", "参数2："))
        self.label_5.setText(_translate("Form", "参数3："))
        self.choosefile.setText(_translate("Form", "选择文件"))
        self.option.setText(_translate("Form", "选项"))
